### ISSUE TITLE
notes on the newest layout

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#36] opened 2014-10-08 03:40 UTC
Okayyy so, not sure if this is the right place but lets seeee:

-i really liked having an open/splash effect of a large image once you get to the website. is there any way that if you hover over the "disOrientation" Title full screen image of the cover pops up? and when you aren't hovering over the title its just disappearing? could be a way to get the simplicity you already have but add some big bang imagery too?
- also i think it would be nice to have two columns for opening text, also i think we can get rid of the FREE COOPER UNION under line above disOrientation since the URL is freecooperunion.org, plus you says it all over the place, and also it just looks lonely up there.
  ![screen shot 2014-10-07 at 8 40 00 pm](https://cloud.githubusercontent.com/assets/9045718/4553587/c6d2ec76-4e9c-11e4-963b-21b45f3ce9b7.png)

~~\- can we bump "by Free Cooper Union" to the next line, so theres no widow, widows are hard to prevent on the web but since this is right in the beginning i think its worth it.~~
![screen shot 2014-10-07 at 8 02 11 pm](https://cloud.githubusercontent.com/assets/9045718/4553344/a0d9d778-4e97-11e4-96f4-a6125a54c29b.png)

~~-general note *if it aint too hard can we do something fun with highlighting text, i know its not very functional but I fugggin love website that address the highlighting text, maybe make it black, or find some fun noisy fill in texture??~~
![screen shot 2014-10-07 at 8 04 27 pm](https://cloud.githubusercontent.com/assets/9045718/4553352/cced5588-4e97-11e4-93a4-263143d97711.png)

~~-can you add like a pixel or two of space for the underlined sections (i.e. "lowdown")~~
![screen shot 2014-10-07 at 8 05 20 pm](https://cloud.githubusercontent.com/assets/9045718/4553360/ebaea7f6-4e97-11e4-89af-13eb6acef2bf.png)

-if it isn't too hard i think it would be super rad to have an image that relates to the essay/section pop up whenever you hover over the title (i.e.: 1. direct actions) like any image that is in the reader of that section, if you don't have a correlating image i can make something real quick so each section has an image. I think it would be nice because right now its so text heavy and it gives a little visual indication of whats going on behind that link....

~~-LOOOOOVE the large text when you go into the section/essay omgggg
----omg great job stylin it, they look so well connected (I'm only in direct action right now)~~

-The box thing at the bottom of each essay, that says next page, i think is a little underwhelming, it doesn't feel right to me. I did a quick mockup of an alternative layout? Not a big deal but think it could be a easy alteration
![screen shot 2014-10-07 at 8 18 40 pm](https://cloud.githubusercontent.com/assets/9045718/4553465/1e0da056-4e9a-11e4-9ef1-fd0bb8145426.png)

and when you hover over the text, to let you know its active and will bring you to next page, just a color change or something

![screen shot 2014-10-07 at 8 19 36 pm](https://cloud.githubusercontent.com/assets/9045718/4553468/2ce5aba0-4e9a-11e4-97cc-ff8d5afe4d49.png)

-can we do something with links, maybe a different color blue? it just looks like super old classic hyperlink color shocking blue... also when you hover maybe then introduce the underline? (I'm sure you can tell by now I'm a lil bitch about hover action/ sucker for them)
![screen shot 2014-10-07 at 8 22 29 pm](https://cloud.githubusercontent.com/assets/9045718/4553478/73cc8c3c-4e9a-11e4-85c1-3143b78ca3f4.png)

-can you align "DISORIENTATION" at the top header to the numbers? its aligning to lowdown right now, its super small bitchy adjustment but if ur chill with it, that would be gr8
![screen shot 2014-10-07 at 8 25 29 pm](https://cloud.githubusercontent.com/assets/9045718/4553495/db1ab92c-4e9a-11e4-8962-41b72ee562fc.png)
or just move it to the left hand side of LOWDOWN like this
![screen shot 2014-10-07 at 8 27 47 pm](https://cloud.githubusercontent.com/assets/9045718/4553504/1b5df698-4e9b-11e4-8457-7c08047563a5.png)

-is it possible to hang the quotation marks on the big pull quotes if this ever happens like this one:
**also there is a widow on this pull quote, can you knock down 'the first' to join 'resort'
there are some other widow, pull quotes,  i won't pick them all out if you see em and its easy to change just knock down a word or two....
![screen shot 2014-10-07 at 8 28 37 pm](https://cloud.githubusercontent.com/assets/9045718/4553526/4ca78908-4e9b-11e4-821a-db1a9a2f08c8.png)

~~-there is like double text, like two titles on top of each other... this mistake? kinda fuggd up and cool but inconsistent. ~~
![screen shot 2014-10-07 at 8 30 42 pm](https://cloud.githubusercontent.com/assets/9045718/4553543/813a9b2e-4e9b-11e4-987b-ea98cc176eb8.png)

~~-cam we make this image bigger, i love it big so much, and it can split the text i think that would be okay as long as its at a paragraph break~~
![screen shot 2014-10-07 at 8 32 59 pm](https://cloud.githubusercontent.com/assets/9045718/4553558/d6fb73e4-4e9b-11e4-81a6-2b518f0daa67.png)

~~-sam rosners an appeal title text looks like a broken link or image... for me at least~~
![screen shot 2014-10-07 at 8 34 27 pm](https://cloud.githubusercontent.com/assets/9045718/4553562/054d2c60-4e9c-11e4-95ed-b6865937f9e6.png)

~~-same with jakob's...~~

~~-same with Sangu (also you didn't bold his name like everyone else)~~

Loooking suppppppper good!

**Comment by caseyg** [comment] 2014-10-08 03:47
@troykreiner for the free school free society image could you make a version with some background texture or more horizontality to it? the square-ish ratio becomes problematic at large screen sizes because the image becomes taller than the viewport height, a.k.a. difficult to take in.

**Comment by troykreiner** [comment] 2014-10-08 17:09
Hayyy, so I here is an updated image that is more landscape:
https://www.dropbox.com/s/1z0ob8f4ajchit4/FCU-Totebag-v3-revised.psd?dl=0

![screen shot 2014-10-08 at 10 09 21 am](https://cloud.githubusercontent.com/assets/9045718/4563403/da6e529a-4f0d-11e4-8c68-47de9302e155.png)

**Comment by caseyg** [comment] 2015-04-03 04:47
a bunch of this has been fixed, which I indicated by cross outs above:
- [x] non-breaking spaces in first line between words "Free Cooper Union" to prevent widow
- [x] fix title text images
- [x] make free school image huge
- [ ] hanging quotes
- [ ] two column text (I have hesitations about this everywhere) 
- [ ] nav changes (dunno if still relevant, simplified nav but still don't luv it)
- [ ] link styles
- [ ] next/prev article navigation
- [ ] visuals for homepage article nav: dupe of issue #48

**Closed as completed** 2015-04-21 18:11 UTC
Labels: design, frontend
